# Generated by Django 3.0.7 on 2020-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getSeededTeam', '0003_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('TECH', 'Technology'), ('GEN', 'General'), ('SOC', 'Society')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
