# Generated by Django 3.0.7 on 2020-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getSeededTeam', '0005_auto_20200614_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('General', 'General'), ('Social', 'Social')], max_length=10),
        ),
    ]
